### ISSUE TITLE
ValueError: year -1 is out of range

### ISSUE THREAD

**Issue by ColinMaudry** [MTES-MCT/trackdechets-public-stats#3]
La récupération des données des bordereaux via `pd.read_sql_query` échoue, apparemment en raison d'un problème de date mal formée dans les données.

Cela empêche l'appli de démarrer.

Logs scalingo : https://dashboard.scalingo.com/apps/osc-secnum-fr1/trackdechets-public-stats/logs/

J'ai récupéré un dump de production de ce matin, avec le même code je n'arrive pas à reproduire en local.

**Comment by ColinMaudry** [comment]
```
2022-03-10 15:33:05.035528833 +0100 CET [manager] container [web-1] (622a0c20affe57a092e2d9fb) started with the command 'python app.py'
2022-03-10 15:33:10.780418076 +0100 CET [web-1] Today date is not fixed, using datetime.today()
2022-03-10 15:33:11.008028186 +0100 CET [web-1] Traceback (most recent call last): 
2022-03-10 15:33:11.008041199 +0100 CET [web-1] File "/app/app.py", line 129, in <module>
2022-03-10 15:33:11.008042735 +0100 CET [web-1] df_bsdd: pd.DataFrame = get_bsdd_data()
2022-03-10 15:33:11.008043192 +0100 CET [web-1] File "/app/.scalingo/python/lib/python3.9/site-packages/flask_caching/__init__.py", line 952, in decorated_function
2022-03-10 15:33:11.008216096 +0100 CET [web-1] rv = f(*args, **kwargs)
2022-03-10 15:33:11.008225633 +0100 CET [web-1] File "/app/app.py", line 45, in get_bsdd_data
2022-03-10 15:33:11.008226471 +0100 CET [web-1] df_bsdd_query = pd.read_sql_query(
2022-03-10 15:33:11.008226937 +0100 CET [web-1] File "/app/.scalingo/python/lib/python3.9/site-packages/pandas/io/sql.py", line 436, in read_sql_query
2022-03-10 15:33:11.008414383 +0100 CET [web-1] return pandas_sql.read_query(
2022-03-10 15:33:11.008416781 +0100 CET [web-1] File "/app/.scalingo/python/lib/python3.9/site-packages/pandas/io/sql.py", line 1593, in read_query
2022-03-10 15:33:11.008675878 +0100 CET [web-1] data = result.fetchall()
2022-03-10 15:33:11.008683474 +0100 CET [web-1] File "/app/.scalingo/python/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1014, in fetchall
2022-03-10 15:33:11.008900726 +0100 CET [web-1] return self._allrows()
2022-03-10 15:33:11.008903435 +0100 CET [web-1] File "/app/.scalingo/python/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 400, in _allrows
2022-03-10 15:33:11.008931993 +0100 CET [web-1] rows = self._fetchall_impl()
2022-03-10 15:33:11.008932767 +0100 CET [web-1] File "/app/.scalingo/python/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 1803, in _fetchall_impl
2022-03-10 15:33:11.009285270 +0100 CET [web-1] return self.cursor_strategy.fetchall(self, self.cursor)
2022-03-10 15:33:11.009286820 +0100 CET [web-1] File "/app/.scalingo/python/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 981, in fetchall
2022-03-10 15:33:11.009414592 +0100 CET [web-1] self.handle_exception(result, dbapi_cursor, e)
2022-03-10 15:33:11.009415776 +0100 CET [web-1] File "/app/.scalingo/python/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 941, in handle_exception
2022-03-10 15:33:11.009620030 +0100 CET [web-1] result.connection._handle_dbapi_exception(
2022-03-10 15:33:11.009621172 +0100 CET [web-1] File "/app/.scalingo/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2030, in _handle_dbapi_exception
2022-03-10 15:33:11.009900703 +0100 CET [web-1] util.raise_(exc_info[1], with_traceback=exc_info[2])
2022-03-10 15:33:11.009901840 +0100 CET [web-1] File "/app/.scalingo/python/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
2022-03-10 15:33:11.009986165 +0100 CET [web-1] raise exception
2022-03-10 15:33:11.009986992 +0100 CET [web-1] File "/app/.scalingo/python/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 977, in fetchall
2022-03-10 15:33:11.010142319 +0100 CET [web-1] rows = dbapi_cursor.fetchall()
2022-03-10 15:33:11.010143083 +0100 CET [web-1] ValueError: year -1 is out of range
```

**Comment by ColinMaudry** [comment]
La requête : https://github.com/MTES-MCT/trackdechets-public-stats/blob/main/app.py#L57-L77

**Comment by ColinMaudry** [comment]
Attempt to filter out year 0001 dates: 25e3da8e18eb7cb

**Comment by ColinMaudry** [comment]
Ces BSDD posaient problème : 

id | createdAt | processedAt
-- | -- | --
cky4qe0gi161701832jkiittmuwg | 2022-01-07 19:27:49.842+01 | 0001-01-01 00:09:21+00:09:21
cky8ftamv11987602sjkcxh5whw2 | 2022-01-10 09:42:51.799+01 | 0001-01-01 00:00:00+00:09:21
cky9zwsal89161835ji4zyrb9cj | 2022-01-11 11:53:13.149+01 | 0001-01-01 00:09:21+00:09:21
ckybggjyw8317838jirkbhpp8b | 2022-01-12 12:24:15.512+01 | 0001-01-01 00:09:21+00:09:21
ckyelne7y997632jik989x4kk | 2022-01-14 17:12:51.262+01 | 0001-01-01 00:09:21+00:09:21
ckyelnf4c1581633jl4uyysctl | 2022-01-14 17:12:52.428+01 | 0001-01-01 00:09:21+00:09:21
ckyiuo3f5118179034jj89rbyd3u | 2022-01-17 16:36:25.169+01 | 0001-01-01 00:09:21+00:09:21
ckyiz72x8134988033jl8xt11wlq | 2022-01-17 18:43:09.452+01 | 0001-01-01 00:09:21+00:09:21
ckysqkw5i155298533jl21xwcv8o | 2022-01-24 14:39:39.078+01 | 0001-01-01 00:09:21+00:09:21
ckysqkx40156145632jier3f4bs6 | 2022-01-24 14:39:40.32+01 | 0001-01-01 00:09:21+00:09:21
ckysqkxtn156148734jjumy6zev5 | 2022-01-24 14:39:41.243+01 | 0001-01-01 00:09:21+00:09:21
ckysqkyna153409631jkcrqp2nxi | 2022-01-24 14:39:42.31+01 | 0001-01-01 00:09:21+00:09:21
ckz3x7en267764831jl5k1sbsa2 | 2022-02-01 10:30:35.102+01 | 0001-01-01 00:09:21+00:09:21
ckz3x7fa067483336jilqypwvyi | 2022-02-01 10:30:35.929+01 | 0001-01-01 00:09:21+00:09:21
ckz8bhgo215827036jlxvysfgv1 | 2022-02-04 12:21:23.618+01 | 0001-01-01 00:09:21+00:09:21
ckz8bhi3n15837236jliyg0xy49 | 2022-02-04 12:21:25.475+01 | 0001-01-01 00:09:21+00:09:21
ckzcs9fz082664534ji9l0aeiwo | 2022-02-07 15:22:07.644+01 | 0001-01-01 00:09:21+00:09:21
ckzebitt41190636jlmd5b21ih | 2022-02-08 17:09:04.36+01 | 0001-01-01 00:09:21+00:09:21
ckzebiuiw1198136jlvrr7s0ja | 2022-02-08 17:09:05.288+01 | 0001-01-01 00:09:21+00:09:21
ckzebivct167069332jkq82cca53 | 2022-02-08 17:09:06.365+01 | 0001-01-01 00:09:21+00:09:21
ckzebiwex166928232jjp3h7ddo0 | 2022-02-08 17:09:07.737+01 | 0001-01-01 00:09:21+00:09:21
ckzfwb4ot62926134jim6wfwbwu | 2022-02-09 19:38:43.325+01 | 0001-01-01 00:00:00+00:09:21
ckzwf3kkv20831930jiwvj4i9ot | 2022-02-21 09:09:02.191+01 | 0001-01-01 00:00:00+00:09:21
ckzwxtdt612870930ji10rytop7 | 2022-02-21 17:52:59.562+01 | 0001-01-01 00:00:00+00:09:21
ckzy4qkf948844835jl0t150i3s | 2022-02-22 13:54:31.653+01 | 0001-01-01 00:00:00+00:09:21
ckzzoq9ih108948434jlytzrse31 | 2022-02-23 16:01:56.009+01 | 0001-01-01 00:00:00+00:09:21
cl02e3oua36362134jj37dyd6ye | 2022-02-25 13:27:45.154+01 | 0001-01-01 00:00:00+00:09:21
cl09qqzsl6516632jlgg0197sz | 2022-03-02 16:56:11.061+01 | 0001-01-01 00:00:00+00:09:21
